### ISSUE TITLE
How to test the model on new affordance type

### ISSUE THREAD

**Issue by haomengz** [Reagan1311/OOAL#2]
Hi, 

Thanks for the work and the open-source code. 
I am wondering how to test the model for a new affordance type? Currently, it seems that the affordance types are fixed-sized for both seen and unseen setting. To inference on the provided model checkpoint, it seems we have to provide the affordance type (index) that is pre-defined in an affordance list.

**Comment by Reagan1311** [comment]
Hi, the affordance categories are fixed in testing, as the datasets used do not support open-vocabulary evaluation.
For novel affordance inference, you'll need to make an inference code and modify the input text here: https://github.com/Reagan1311/OOAL/blob/b65857c0d3e047d665a92d1c80044f8234c87c56/models/ooal.py#L52.

**Comment by haomengz** [comment]
Thanks. Could you elaborate more on the inference code? For example, for your visualization in figure 11, when inputing a new affordance, do you use the same trained model on the AGD20K categories? If so, do you keep the number of categories the same, and substitute the ```class_names``` with novel affordance label? I am wondering how you manage the ```class_names``` during inference given a new affordance label.

**Comment by Reagan1311** [comment]
Sorry for the late reply. Yes, the same trained model is used. The `class_names` is replaced with the novel affordance label during inference. You need to provide the affordance index only for evaluation, as this is how AGD20K is evaluated.

**Comment by haomengz** [comment]
Great. Thanks for the clarification.

**Comment by andreeatulbure** [comment]
Hello, I am wondering if you got this running. I changed the args.class_names to contain the name of my affordance ( for testing just 1), but the trained model seems to be fixed with the number of affordances in the unseen setting (25). I want to use this model to compare my work to the existing state of the art, but I can not get it running, unfortunately, with open vocabulary/my affordances. These are the errors I get:

RuntimeError: Error(s) in loading state_dict for Net:
	size mismatch for prompt_learner.token_prefix: copying a param with shape torch.Size([25, 1, 512]) from checkpoint, the shape in current model is torch.Size([1, 1, 512]).
	size mismatch for prompt_learner.token_suffix: copying a param with shape torch.Size([25, 68, 512]) from checkpoint, the shape in current model is torch.Size([1, 68, 512]).
