### ISSUE TITLE
Consultation about hit affordance for hammer in OOAL

### ISSUE THREAD

**Issue by Charlie0257** [Reagan1311/OOAL#4]
Hello! @Reagan1311 

Thanks for your great work, One-Shot Open Affordance Learning with Foundation Models.

When I try to predict the hit affordance about hammer in the one-shot-seen dataset by using your offered ckpt, the prediction is shown in the attached file.

Curious if the hammer hit prediction is that bad?

I'm sorry for taking your time.

Best,
Charlie
![hammer_001263_overlay_mask_hit](https://github.com/user-attachments/assets/70299051-c5a1-4ef7-94cb-ae66faf10329)

**Comment by Reagan1311** [comment]
Hi Charlie. This is because we do the one-shot annotation following AGD20K's standard, which annotates the affordances of "hit", "swin" on the handle part. For real-world application, such as robotic manipulation, I suggest you doing one-shot annotation based on your affordance standard. For example, "hit" corresponds to hammer head, and "hold" corresponds to hammer handle.

**Comment by Charlie0257** [comment]
Thanks a lot for this tip!
